services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      BUNDLE_PATH: /usr/local/bundle
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  redis_data:
  bundle:
  node_modules:
