services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 5s

  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  rails:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "3.2.2"  # Ruby のバージョンを指定
        BUNDLER_VERSION: "2.3.26"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432
      REDIS_URL: redis://redis:6379/
    command: bundle exec rails s
    ports:
      - "3000:3000"
    

  sidekiq:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: "3.2.2"
        BUNDLER_VERSION: "2.3.26"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - type: bind
        source: ./dockerdev/.bashrc
        target: /root/.bashrc
        read_only: true
    depends_on:
      - postgres
      - redis
    command: bundle exec sidekiq

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  packs:
